name: Build and Test

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Configure BuilderExample
    run: cmake /home/runner/work/Rk/rk2 -B ${{github.workspace}}/build

  - name: Build BuilderExample
    run: cmake --build ${{github.workspace}}/build
